<?php


require_once 'core.php';

$SUBJORNAL = $_POST['SUBJORNAL'];
$COSJORNAL = $_POST['COSJORNAL'];
$COSMANO = $_POST['COSMANO'];
$COSFAMI = $_POST['COSFAMI'];
$COSLENA = $_POST['COSLENA'];
$COSTRANS = $_POST['COSTRANS'];
$COSMANT = $_POST['COSMANT'];
$COSCANA = $_POST['COSCANA'];
$COSTRAPICHE = $_POST['COSTRAPICHE'];
$COSTINA = $_POST['COSTINA'];
$COSINFRA = $_POST['COSINFRA'];
$DESCRIPCION = $_POST['DESC'];
$HOJAID = $_POST['idhoja'];



$sql = "UPDATE SUBTOTALHOJADECAMPO 
SET 
SUBJORNAL=$SUBJORNAL,
COSJORNAL=$COSJORNAL,
COSMANO=$COSMANO,
COSFAMI=$COSFAMI,
COSLENA=$COSLENA,
COSTRANS=$COSTRANS,
COSMANT=$COSMANT,
COSCANA=$COSCANA,
COSTRAPICHE=$COSTRAPICHE,
COSTINA=$COSTINA,
COSINFRA=$COSINFRA,
OBSERVACIONES='$DESCRIPCION',
HOJASTATUS=1 WHERE SUBHOJADECAMPOID =$HOJAID";

$EJECUTADO = mysqli_query($connect, $sql) or die("Problemas al insertar HOJA DE CAMPO " . mysqli_error($connect));

header("location:../hojaCampo.php");

